---
#roles/ec2-instance-launch/tasks/main.yml @LNReddy-Diddala

- name: Launch the new EC2 Instance
  ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type}}"
      image: "{{ image }}"
      wait: true 
      region: "{{region}}"
      count: "{{ count }}"
      volumes:
        - device_name: "{{ device_name }}"
          volume_size: "{{ volume_size }}"
  register: ec2
      
- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  add_host:
    name: "{{ item.public_ip }}"
    groups: webserver
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for: host="{{ item.public_ip }}" 
            port=22 
            state=started
  with_items: "{{ec2.instances}}"

- name: Add tag to Instance(s)
  ec2_tag: 
    resource: "{{ item.id }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: webserver
  with_items: "{{ec2.instances}}"