---
# Using this playbook you can create Security Group and Launch EC2 Instances in AWS. @LNReddy-Diddala
- name: Provision an EC2 Instance
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning

  # Roles that will be used to create Security Group and launch EC2 Instance. @LNReddy-Diddala

  roles:
    - create-sg
    - ec2-instance-launch
