---

- hosts: host-servers
  become: yes

  tasks:

    - name: Stop "httpd" service, if running
      service:
        name: httpd
        state: stopped

    - pause:
        seconds: 20

    - name: Copy files from Master server to Host servers
      copy:
        src: /home/host/Ansible/smartler/index.html
        dest: /var/www/html/index.html
        owner: host
        group: host
        mode: "0644"
        backup: yes

    - pause:
        seconds: 20

    - name: Restart "httpd" service, in all cases
      service:
        name: httpd
        state: restarted
