---
# This task is responsible for copy the files from master server to client nodes.

- name: Copy files from Master server to Host servers
  copy:
    src: /home/host/Ansible/smartler/index.html
    dest: /var/www/html/index.html
    owner: host
    group: host
    mode: "0755"
    backup: yes

- pause:
    seconds: 10
